### ISSUE TITLE
no AI workers available to process request

### ISSUE THREAD

**Issue by zaybronx** [guspuffygit/sentient-sims-app#24]
## Summary

 I'm getting a message that says no AI workers available for request_

**Comment by zaybronx** [comment]
When running an action, I'm getting a notification that says no AI workers available for request and none of the sentient wants or functions are working

**Comment by guspuffygit** [comment]
Hello thank you for reporting. The error is correctly popping up. The AI workers became disconnected from the API for a short period of time and it should now be resolved. When this happens, it notifies me directly so that I can fix the error too.
